// <auto-generated />
namespace ConstructIT.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class clientusersepparation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clientusersepparation));
        
        string IMigrationMetadata.Id
        {
            get { return "201609161444078_client-user-sepparation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
